name: full_scale_shop_app
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  auto_route: ^7.1.0
  card_swiper: ^2.0.4
  cloud_firestore: ^4.8.0
  cupertino_icons: ^1.0.2
  fancy_shimmer_image: ^2.0.2
  firebase_auth: ^4.6.1
  firebase_core: ^2.13.0
  flutter:
    sdk: flutter
  flutter_hooks: ^0.18.6
  flutter_iconly: ^1.0.2
  flutter_spinkit: ^5.2.0
  flutter_staggered_grid_view: ^0.6.2
  fpdart: ^0.6.0
  gap: ^3.0.0
  google_sign_in: ^6.1.0
  hooks_riverpod: ^2.3.6
  shared_preferences: ^2.1.0

dev_dependencies:
  auto_route_generator: ^7.0.0
  build_runner: ^2.3.3
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/images/categories/
    - assets/images/landing/
    - assets/images/offers/
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
