// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQRai0ViBfPtO3A5Fc5Tryzn5Q4rRBJjs',
    appId: '1:602077372143:android:9a21cbc6db36fd781f051a',
    messagingSenderId: '602077372143',
    projectId: 'e-commerce-app-2dc5d',
    storageBucket: 'e-commerce-app-2dc5d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBrkiEiWsHoMOnrG1lC18SK0NpW7G-_rRw',
    appId: '1:602077372143:ios:d9ef83235e2c7e561f051a',
    messagingSenderId: '602077372143',
    projectId: 'e-commerce-app-2dc5d',
    storageBucket: 'e-commerce-app-2dc5d.appspot.com',
    androidClientId: '602077372143-9g8td8qksrbqtbsfsdo8ba4p8j1oaanm.apps.googleusercontent.com',
    iosClientId: '602077372143-e43crio1v4nbk1fg6hilvton6kp7412u.apps.googleusercontent.com',
    iosBundleId: 'com.example.fullScaleShopApp',
  );
}
